version: '3.9'
services:
  devproxy:
    image: moriyoshi/devproxy:0.6.1
    volumes:
      - ./certs:/etc/certs
      - .:/app
    ports:
      - 8080:8080
    command: '/bin/devproxy /app/devproxy.yml'
    network_mode: host
  front:
    env_file:
      - .env
    build:
      context: .
    ports:
      - 3000:3000
    network_mode: host
    volumes:
      - .:/app
  dozzle:
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9999:8080
