version: '3.9'
services:
  devproxy:
    image: moriyoshi/devproxy:0.6.1
    volumes:
      - ./certs:/etc/certs
      - .:/app
    ports:
      - 8080:8080
    command: '/bin/devproxy /app/devproxy.yml'
    network_mode: host
# networks:
#   default:
#     driver: bridge
