version: '3.9'
services:
  devproxy:
    image: moriyoshi/devproxy:0.6.1
    volumes:
      - ./certs:/etc/certs
      - .:/app
    ports:
      - 8080:8080
    command: '/bin/devproxy /app/devproxy.yml'
    networks:
      - ntwk
  front:
    env_file:
      - .env
    build:
      context: .
      dockerfile: docker/front/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/app
    networks:
      - ntwk
      - ext
  dozzle:
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9999:8080
  firebase:
    build:
      context: .
      dockerfile: docker/firebase/Dockerfile
    ports:
      - 4000:4000
      - 5000:5000
      - 9099:9099
      - 8099:8099
    command:
      - "emulators:start"
      - "--project"
      - "${PROJECTID}"
      - "--token"
      - "${FIREBASE_TOKEN}"
    networks:
      - ntwk
    command: bash
    tty: true

networks:
  ext:
  ntwk:
